### ISSUE TITLE
No audio on cold boot Windows 10 1809

### ISSUE THREAD

**Issue by Dubbeldrank** [alanfox2000/realtek-universal-audio-driver#10]
Since the 8569 driver audio doesn't work at cold boot on Windows 10 build 1809. After a restart or disabling and enabling the device audio functions like expected.

**Comment by alanfox2000** [comment]
Try HDA instead of UAD.
https://github.com/alanfox2000/realtek-hda-release/releases/download/6.0.1.8573/8573_FF0C_FF00_FF01_FF03_FF04_FF06_FF10_PG468_Win10_RS2_RS3_RS4_RS5_Win7_WHQL.rar

**Comment by Dubbeldrank** [comment]
The problem seems to have disappeared a few days later without any change.
