### ISSUE TITLE
realtek audio control won't install

### ISSUE THREAD

**Issue by tomyan112** [alanfox2000/realtek-universal-audio-driver#11]
After I install the UAA driver, it only shows in video and game controllers but not in the audio inputs and outputs. Also the realtek audio control won't install. How to fix this?

![annotation 2018-11-24 152529](https://user-images.githubusercontent.com/9064351/48965713-3c2ac380-effd-11e8-8c7b-83fe8034867a.jpg)

**Comment by alanfox2000** [comment]
Check if RealtekHSA.inf has be installed
https://github.com/alanfox2000/realtek-universal-audio-driver/wiki/Installation#c-automatically-download-and-install-realtek-audio-console-from-store
