### ISSUE TITLE
ASIO Drivers Not Installing

### ISSUE THREAD

**Issue by lazerl0rd** [alanfox2000/realtek-universal-audio-driver#17]
How do we go about installing ASIO drivers too? I tried manually installing the ASIO package via UPnP but Audition CC doesn't detect Realtek ASIO. Also for some reason, they are all coupled together as one device in WASAPI even tho I explicitly split them so Sound Control Panel sees them as different objects.

It works great on my mobo and the Realtek APPX loads up with MSI's branding just like the desktop app.

My HWID for my Audio driver is HDAUDIO\FUNC_01&VEN_10EC&DEV_0900&SUBSYS_1462D693.

Weirdly, ASIO seems to support ANY of the drivers and since I had to do the manual method, I couldn't get the Setup.exe and couldn't set "ForceASIO" to 1.

**Comment by lazerl0rd** [comment]
Okay, so you can manually force it by copying **RTHDASIO.dll to %SystemRoot%\SysWow64\RTHDASIO.dll** and **RTHDASIO64.dll to %SystemRoot%\System32\RTHDASIO64.dll** from the RealtekASIO_4 folder.

I suspect this is what the ForceASIO option in the old setup.inf used to refer to, but I would like to confirm with you (@alanfox2000) before I close this issue :).

**Comment by lazerl0rd** [comment]
Okay so mini-update. I updated Win10 and now it's ignoring the added files in System32 and SysWOW64 and ASIO no longer appears in Adobe Audition. I believe the true solution is not replicating ForceASIO but finding a way to get Windows to recognize the Software Components.

**Comment by alanfox2000** [comment]
Only HDX_GenericExt_RTK.inf support your audio chips Device ID 0900
SubSystem ID 1462D693 not found CodecExtOem_RTK folder
ASIO software components Realtek Device Extension inf (CodecExtOem_RTK folder)

To check if your HWID support ASIO on UAD, find the inf file contains your HWID inside CodecExtOem_RTK folder

I.E HDX_DellCSMBExt_WAVES_MA8MV5.inf, INTELAUDIO\FUNC_01&VEN_10EC&DEV_0295&SUBSYS_102808B6 support ASIO on UAD
[DeviceExtensions.NTamd64.10.0...15063]
%Device.ExtensionDesc% = DeviceExtension_Install_Render_DSP_Capture_APO_KD, INTELAUDIO\FUNC_01&VEN_10EC&DEV_0295&SUBSYS_102808B6

[DeviceExtension_Install_Render_DSP_Capture_APO_KD.Components]
AddComponent = RealtekAPO,,RealtekAPO_Install
AddComponent = RealtekSRV,,RealtekSRV_Install
AddComponent = RealtekASIO,,RealtekASIO_Install

[RealtekASIO_Install]
ComponentIDs = VEN_10EC&ASIO_ID_0001
Description = "Realtek Asio Component"

**Comment by lazerl0rd** [comment]
@alanfox2000 Thanks for explaining that my chip doesn't support on UAD. It previously did on HDA but hey I guess things changed.

What I meant was that on HDA **even if you didn't have ASIO support on your HWID** an option existed for the installer called ForceASIO. This option copied the two ASIO driver .dlls over to their relevant locations and Windows would load them up on boot. The software component does the same thing but registers them so if you remove the driver they go away too.
![image](https://user-images.githubusercontent.com/24303423/52179786-660b1e00-27d6-11e9-89bf-41d94617afe5.png)

I decided to do this manually do this and IT WORKED.... until I updated Windows. This may be a Windows bug but now it does not load up the ASIO libraries on boot anymore.

**Comment by lazerl0rd** [comment]
I made a custom driver with ASIO support for Generic (requires disabling driver signature enforcement. This is my workaround, as ForceASIO didn't work. I guess this is a better method too :P.
[HDX_GenericExt_RTK + ASIO.zip](https://github.com/alanfox2000/realtek-universal-audio-driver/files/2825829/HDX_GenericExt_RTK.%2B.ASIO.zip)

However, @alanfox2000 when I tried installing HDXRT.inf it didn't accept it until I renamed HDXRT.inf to something else. It kept saying "cannot find". Is that normal?

**Comment by lazerl0rd** [comment]
![image](https://user-images.githubusercontent.com/24303423/52181323-68767380-27e8-11e9-97f5-8c163c2c054e.png)
Yupp, must be build 18329 which broke the Realtek ASIO driver.

**Comment by lazerl0rd** [comment]
@FPSUsername there is a difference between being added to the driver store and installed.

In your circumstance it has been added to the driver store (you installing with inf editor) as your vendor ID matches up. But ASIO is a software component and therefore only gets installed from the driver store when an extension driver calls it to be.

Your *Ext*.inf does not explicitly install the ASIO component and therefore you don't have it in device manager. TL;DR you copied it into Windows' driver store but didn't install.

I had the same issue with the generic driver which i patched to explicitly install ASIO component.

You have two choices, either patch your *Ext*.inf driver, or copy RTHDASIO.dll to **%SystemRoot%\SysWow64\RTHDASIO.dll** and **RTHDASIO64.dll** to **%SystemRoot%\System32\RTHDASIO64.dll**.

**Comment by lazerl0rd** [comment]
@alanfox2000 along with my above zip file to get ASIO on 64 bit applications I needed this.
[ASIO-Add64.zip](https://github.com/alanfox2000/realtek-universal-audio-driver/files/2829613/ASIO-Add64.zip)
