### ISSUE TITLE
Creative drivers "corrupted"?

### ISSUE THREAD

**Issue by lazerl0rd** [alanfox2000/realtek-universal-audio-driver#18]
It seems Windows 10 x64 declines to install the CreativeExtension.Inf as it isn't hashed within its corresponding Catalog file. I'm not sure if this is an issue with your upload, the source, or something in my side (seems unlikely, though).

There is NO tampering with the driver by me and I tried twice on my PC and once in a VM with the same error.

My HardwareID for my soundcard is HDAUDIO\FUNC_01&VEN_10EC&DEV_0900&SUBSYS_1462D693.

**Comment by lazerl0rd** [comment]
I'm thinking of trying to force the installation by adding it to ThirdParty as I've got a method to create a manual folder for installation with EXE as opposed to PnPUtil (thanks to ASUS) where I can just create an installer. However, I was wondering what you thought on the matter prior to this.

PS - If you would like I could write up a third method you could add to the guide to create an installer without using your application.

**Comment by alanfox2000** [comment]
[CreativeExtension.Inf](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/alanfox2000/realtek-universal-audio-driver/tree/master/ThirdParty/Creative) fixed
![imgur.com](https://i.imgur.com/f92lYpI.png)

You don't need to create an installer with PnPUtil
PnPUtil.exe ‪is Windows built-in program (%systemroot%/system32/pnputil.exe)
UAD Driver Package Creator (Universal Audio Driver Inf Editor by realtek) create a batch scripts which use PnPUtil.exe installing inf file, you just need to enter the HWID then a slim UAD package only for this HWID is geranated.

**Comment by lazerl0rd** [comment]
@alanfox2000 I understand you don't need to create an installer with PnPUtil, what I meant was you can manually create an installer package without your UADInfEditor. I used the SetupX and filled it with the drivers in the correct subdirs the same way ASUS did with their UAD release and that's what I meant by creating a custom installer package.

Thanks for fixing Creative's package though 👍 .
