### ISSUE TITLE
RTK UAD Service v97 is out

### ISSUE THREAD

**Issue by pal1000** [alanfox2000/realtek-universal-audio-driver#3]
Source: https://station-drivers.com/index.php?option=com_kunena&view=topic&defaultmenu=860&Itemid=858&catid=18&id=17&lang=en&limitstart=66#214
Goes in /UAD/Realtek and replaces RealtekService_96.

**Comment by alanfox2000** [comment]
https://github.com/alanfox2000/realtek-universal-audio-driver/commit/04c5acb79e8476a57249d5ecd77bafb42dfcdb5f
