### ISSUE TITLE
Codec 8514

### ISSUE THREAD

**Issue by pal1000** [alanfox2000/realtek-universal-audio-driver#5]
Found on Windows update catalog: http://download.windowsupdate.com/c/msdownload/update/driver/drvs/2018/08/71c35127-d5b3-45ad-9cb4-b4eff699681d_99bf86531b277b03b7cb8ab2c02f7dc55f251ca4.cab

**Comment by alanfox2000** [comment]
https://github.com/alanfox2000/realtek-universal-audio-driver/commit/444dd53fc7fb0372ef93a04615097b8a3f3403a3
