### ISSUE TITLE
Maybe need to add ThirdParty GigabyteAJSExt

### ISSUE THREAD

**Issue by DebuggeR94** [alanfox2000/realtek-universal-audio-driver#6]
Without GigabyteAJSExt extension Realtek Audio Console don't work on Gigabyte Motherboard.
http://www.mediafire.com/file/67dmg3kwy84dl11/GigabyteAJSExt.rar/file

The file I extracted from the official driver (Asia, China, America, Europe servers):
http://download.gigabyte.asia/FileList/Driver/mb_driver_audio_realtek_8475_dch.zip
http://download.gigabyte.cn/FileList/Driver/mb_driver_audio_realtek_8475_dch.zip
http://download.gigabyte.us/FileList/Driver/mb_driver_audio_realtek_8475_dch.zip
http://download.gigabyte.eu/FileList/Driver/mb_driver_audio_realtek_8475_dch.zip

**Comment by alanfox2000** [comment]
There are just 3 HWID on extension INF. Just very few (3) Gigabyte Motherboard needed this.
I have Gigabyte Motherboard and don't have this.
But I have added it on the download section.

https://github.com/alanfox2000/realtek-universal-audio-driver/commit/98e952738e4d97435d3e0bb0eded56e2b7a42e28
