### ISSUE TITLE
Problem with launching Realtek Audio Console

### ISSUE THREAD

**Issue by cika8** [alanfox2000/realtek-universal-audio-driver#7]
I have a problem with launching Realtek Audio Console. Message: Realtek Audio Console doesn't support for this machine. https://ibb.co/gpO0xK (1.2.139.0).
Previous version worked fine (1.2.137.0). Motherboard is Asus B150M-K, with Realtek ALC887. Driver version is: 6.0.1.8522. 
I would be grateful if you can check this problem and... I like your project. :)

**Comment by alanfox2000** [comment]
Codec 8522 UAD not waiting with Realtek Audio Console 1.2.139.0
Use Realtek Audio Console 1.2.137.0 for Codec 8522 UAD instead

The newer UAD have new inf file HDXRTBase.inf
Just wait for Generic UAD release for the new version of UWP app

**Comment by alanfox2000** [comment]
Just Test New Version of Realtek Audio Control. It works fine.
https://github.com/alanfox2000/realtek-universal-audio-driver/releases/tag/1.2.140.0

**Comment by cika8** [comment]
Yes, now is working (1.2.140). Thank you! :)
