### ISSUE TITLE
Realtek Audio Console - Connector retasking

### ISSUE THREAD

**Issue by cika8** [alanfox2000/realtek-universal-audio-driver#9]
Hello there. I have a question about connector retasking. When I plug Speakers or Headphones in Mic-in and/or Line-in connector (back side) there is no connector retasking option in Audio Console. This is status:
1. Speaker out - can be Speaker and Headphone (back side);
2. Mic-in - can be only Mic-in (back side);
3. Line-in - can be only Line-in (back side);
4. Headphone - can be Headphone-out and Speaker-out (front side);
5. Mic-in - can be Line-in, Mic-in and Headphone-out (front side);

https://ibb.co/jhpBAL

I remember when I had all the connectors available for retasking in old Realtek Control panel (every connector could be for everything). 

My specs are:
Windows 10 1809, with latest updates; 
Motherboard: ASUS B150M-K (last version of BIOS) with Realtek ALC887;
Driver version: 6.0.1.8569;
Console version: 1.2.156.0;

Appreciate your work and help! :)

**Comment by alanfox2000** [comment]
I’m afraid that I can’t help you.

I suggest you post your question on [Station Driver Forum](https://www.station-drivers.com/index.php?option=com_kunena&view=topic&defaultmenu=860&Itemid=858&catid=18&id=17&lang=en&limitstart=366) or [My Digital Life froum](https://forums.mydigitallife.net/threads/update-realtek-high-definition-audio.72236/page-24)

**Comment by cika8** [comment]
Ok, thanks!

**Comment by cika8** [comment]
Actually, I found this information on ASUS site: Supports: **_Jack-detection, Front Panel Jack-retasking_**
Sooo, that's it. On ex. motherboard (MSI 760GM-P23 (FX)) which had ALC887 too I could retask any connector, so I thought that I can do that on this motherboard too, but...
You can close this thread. :)
